#!/system/bin/sh
#
# Copyright (c) 2017 UpInTheAir. All rights reserved.
#
# Authors:	UpInTheAir
#
# This software and associated documentation files (the "Software")
# is proprietary of UpInTheAir. No part of this Software, either
# material or conceptual may be copied or distributed, transmitted,
# transcribed, stored in a retrieval system or translated into any
# human or computer language in any form by any means, electronic,
# mechanical, manual or otherwise, or disclosed to third parties
# without the express written permission of UpInTheAir.
#
# Alternatively, this program is free software in case of open
# source project:
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this Software, to redistribute the Software
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

if [ -e /su/xbin/busybox ]; then
	BB=/su/xbin/busybox;
elif [ -e /system/xbin/busybox ]; then
	BB=/system/xbin/busybox;
elif [ -e /system/bin/busybox ]; then
	BB=/system/bin/busybox;
fi;

if [ "$($BB mount | grep rootfs | cut -c 26-27 | grep -c ro)" -eq "1" ]; then
	$BB mount -o remount,rw /;
fi;

# stop Crontab
pkill -f crond;
pkill -f "/res/crontab_service/service.sh";
$BB rm -rf /data/crontab/*;

# import user set parameters
intvl_hour_1=$(cat /res/synapse/SkyHigh/cron/intvl_hour_1);
intvl_hour_2=$(cat /res/synapse/SkyHigh/cron/intvl_hour_2);

time_min_3=$(cat /res/synapse/SkyHigh/cron/time_min_3);
time_min_4=$(cat /res/synapse/SkyHigh/cron/time_min_4);
time_min_5=$(cat /res/synapse/SkyHigh/cron/time_min_5);
time_min_6=$(cat /res/synapse/SkyHigh/cron/time_min_6);
time_min_7=$(cat /res/synapse/SkyHigh/cron/time_min_7);

time_hour_3=$(cat /res/synapse/SkyHigh/cron/time_hour_3);
time_hour_4=$(cat /res/synapse/SkyHigh/cron/time_hour_4);
time_hour_5=$(cat /res/synapse/SkyHigh/cron/time_hour_5);
time_hour_6=$(cat /res/synapse/SkyHigh/cron/time_hour_6);
time_hour_7=$(cat /res/synapse/SkyHigh/cron/time_hour_7);

day_6=$(cat /res/synapse/SkyHigh/cron/day_6);
day_7=$(cat /res/synapse/SkyHigh/cron/day_7);

# reset cron-root
if [ -e /su/xbin/busybox ]; then
	cron_root=/res/crontab_service/su/cron-root;
	$BB rm -rf $cron_root;
elif [ -e /system/xbin/busybox ]; then
	cron_root=/res/crontab_service/system_xbin/cron-root;
	$BB rm -rf $cron_root;
elif [ -e /system/bin/busybox ]; then
	cron_root=/res/crontab_service/system_bin/cron-root;
	$BB rm -rf $cron_root;
fi;

# apply paramaters
echo "# This file is at /var/spool/cron/crontabs/root
#field          allowed values
#-----          --------------
#minute         0-59
#hour           0-23
#day of month   1-31
#month          1-12 (or names, see below)
#day of week    0-7 (0 or 7 is Sun, or use names)

#JOBS
* 0-23/$intvl_hour_1 * * * $BB sh /data/crontab/cron-scripts/drop-cache.sh
* 0-23/$intvl_hour_2 * * * $BB sh /data/crontab/cron-scripts/ram_release.sh
$time_min_3 $time_hour_3 * * * $BB sh /data/crontab/cron-scripts/clear-file-cache.sh
$time_min_4 $time_hour_4 * * * $BB sh /data/crontab/cron-scripts/database_optimizing.sh
$time_min_5 $time_hour_5 * * * $BB sh /data/crontab/cron-scripts/fstrim.sh
$time_min_6 $time_hour_6 * * $day_6 $BB sh /data/crontab/cron-scripts/reset_battery.sh
$time_min_7 $time_hour_7 * * $day_7 $BB sh /data/crontab/cron-scripts/OpenRecoveryScript.sh" >> $cron_root

# re-start Crontab
$BB nohup $BB sh /res/crontab_service/service.sh 2> /dev/null;

echo "All Cron tasks changes set";
