#!/system/bin/sh
#
# Copyright (c) 2017 UpInTheAir. All rights reserved.
#
# Authors:	UpInTheAir
#
# This software and associated documentation files (the "Software")
# is proprietary of UpInTheAir. No part of this Software, either
# material or conceptual may be copied or distributed, transmitted,
# transcribed, stored in a retrieval system or translated into any
# human or computer language in any form by any means, electronic,
# mechanical, manual or otherwise, or disclosed to third parties
# without the express written permission of UpInTheAir.
#
# Alternatively, this program is free software in case of open
# source project:
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this Software, to redistribute the Software
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

if [ -e /su/xbin/busybox ]; then
	BB=/su/xbin/busybox;
elif [ -e /system/xbin/busybox ]; then
	BB=/system/xbin/busybox;
elif [ -e /system/bin/busybox ]; then
	BB=/system/bin/busybox;
fi;

if [ "$($BB mount | grep rootfs | cut -c 26-27 | grep -c ro)" -eq "1" ]; then
	$BB mount -o remount,rw /;
fi;

mount -o remount,rw \/system;

# import user set parameters
inactive_to=$(($(cat /res/synapse/SkyHigh/doze_inactive_to) * 60000 ));
sensing_to=$(($(cat /res/synapse/SkyHigh/doze_sensing_to) * 60000 ));
locating_to=$(($(cat /res/synapse/SkyHigh/doze_locating_to) * 1000 ));
location_accuracy=$(cat /res/synapse/SkyHigh/doze_location_accuracy);
motion_inactive_to=$(($(cat /res/synapse/SkyHigh/doze_motion_inactive_to) * 60000 ));
idle_after_inactive_to=$(($(cat /res/synapse/SkyHigh/doze_idle_after_inactive_to) * 60000 ));
idle_pending_to=$(($(cat /res/synapse/SkyHigh/doze_idle_pending_to) * 60000 ));
max_idle_pending_to=$(($(cat /res/synapse/SkyHigh/doze_max_idle_pending_to) * 60000 ));
idle_pending_factor=$(cat /res/synapse/SkyHigh/doze_idle_pending_factor);
idle_to=$(($(cat /res/synapse/SkyHigh/doze_idle_to) * 60000 ));
max_idle_to=$(($(cat /res/synapse/SkyHigh/doze_max_idle_to) * 3600000 ));
idle_factor=$(cat /res/synapse/SkyHigh/doze_idle_factor);
min_time_to_alarm=$(($(cat /res/synapse/SkyHigh/doze_min_time_to_alarm) * 60000 ));
max_temp_app_whitelist_duration=$(($(cat /res/synapse/SkyHigh/doze_max_temp_app_whitelist_duration) * 60000 ));
mms_temp_app_whitelist_duration=$(($(cat /res/synapse/SkyHigh/doze_mms_temp_app_whitelist_duration) * 1000 ));
sms_temp_app_whitelist_duration=$(($(cat /res/synapse/SkyHigh/doze_sms_temp_app_whitelist_duration) * 1000 ));

# apply paramaters
settings put global device_idle_constants inactive_to=$inactive_to,sensing_to=$sensing_to,locating_to=$locating_to,location_accuracy=$location_accuracy.0,motion_inactive_to=$motion_inactive_to,idle_after_inactive_to=$idle_after_inactive_to,idle_pending_to=$idle_pending_to,max_idle_pending_to=$max_idle_pending_to,idle_pending_factor=$idle_pending_factor.0,idle_to=$idle_to,max_idle_to=$max_idle_to,idle_factor=$idle_factor.0,min_time_to_alarm=$min_time_to_alarm,max_temp_app_whitelist_duration=$max_temp_app_whitelist_duration,mms_temp_app_whitelist_duration=$mms_temp_app_whitelist_duration,sms_temp_app_whitelist_duration=$sms_temp_app_whitelist_duration;

$BB echo "Parameters applied !"
