#!/system/bin/sh

if [ -e /su/xbin/busybox ]; then
	BB=/su/xbin/busybox;
elif [ -e /system/xbin/busybox ]; then
	BB=/system/xbin/busybox;
fi;

CONFIG_JSON=/res/synapse/config.json;
ACTION_SCRIPTS=/res/synapse/actions/;

if [ ! -e /data/.SkyHigh/invisible_cpuset ]; then
	echo "0" > /data/.SkyHigh/invisible_cpuset;
fi

if [ ! -e /data/.SkyHigh/lazytime_mount ]; then
	echo "0" > /data/.SkyHigh/lazytime_mount;
fi

if [ ! -f $CONFIG_JSON ]; then
	source /res/synapse/json.generate > $CONFIG_JSON;
fi

case "${1}" in

config)
  cat $CONFIG_JSON;
  ;;

configpath)
  echo $CONFIG_JSON;
  ;;

actionpath)
  echo $ACTION_SCRIPTS:/sbin;
  ;;

reset)
  $BB mount -t rootfs -o rw,remount rootfs;
  $BB rm -f $CONFIG_JSON;
  $BB mount -t rootfs -o rw,remount rootfs;
  ;;

esac;
